### ISSUE TITLE
Error detected while processing /root...... Error while calling lua chunk: ...

### ISSUE THREAD

**Issue by vectorstone** [magidc/nvim-config#4]
Windows 11 Pro 22H2 wsl2 Ubuntu18.04

what's that mean? 
![image](https://github.com/magidc/nvim-config/assets/39456045/f175e23e-8564-4f92-9c96-d01a1d55a76e)

**Comment by magidc** [comment]
It seems there is some problem with Codelldb. It is basically a debug adapter (DAP) that allows Neovim to debug Rust or C++ code. Codelldb is also the component that support debugging in VSCode.
In my configuration this component is installed in the system via Mason plugin. Make sure it is installed by running :MasonInstall codelldb
