### ISSUE TITLE
How to generate getters/setters

### ISSUE THREAD

**Issue by gravitational0** [magidc/nvim-config#7]
my code

```Java
package org.example;

public class Department {
    private long id;
    private String name;

}
```

i want to make like this code

```Java
package org.example;

public class Department {
    private long id;
    private String name;

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }
}
```

**Comment by magidc** [comment]
This feature is already available through the "code actions". Just type space+r+e
![imaxe](https://github.com/magidc/nvim-config/assets/4416693/d97ad478-58aa-461e-a2b8-bc71d5f9e4f0)

LSP  should be attached to the current buffer. In this case, jdtls (java). Make sure you have installed it with Mason (:MasonInstall jdtls)
