### ISSUE TITLE
create maven or spring project by neovim

### ISSUE THREAD

**Issue by gravitational0** [magidc/nvim-config#8]
hello , can you add create maven and spring project by neovim
I have to open the ide to create a project every time, then close it and use neovim.

thanks♥♥

**Comment by magidc** [comment]
You can create a new maven project directly from command line:
`mvn archetype:generate -DgroupId=ToolsQA -DartifactId=DemoMavenProject -DarchetypeArtifactId=maven-archetype-quickstart -DinteractiveMode=false`
This will create a minimal file structure. 
Take a look to [this](https://maven.apache.org/archetypes/maven-archetype-quickstart/)
